### ISSUE TITLE
Using fontawesome brands icons

### ISSUE THREAD

**Issue by remyd1** [matsuyoshi30/harbor#110]
Hi,

I am having trouble using brands icons. Is there anything special to do (solid and general icons are working fine) ?

In my `config.toml`, I added:

```
[[params.nav]]
  identifier = "linux"
  name = "Linux"
  icon = "fas fa-linux fa-lg"
  url = "/linux/"
  weight = 3
```

Sorry, if I missed anything here.

Thanks,
Best regards,

**Comment by matsuyoshi30** [comment]
@remyd1 I think Linux icon is Brands style in fontawesome, so it can be used by `fab` like below.

```
icon = "fab fa-linux fa-lg"
```

**Comment by remyd1** [comment]
Perfect!
It was as simple as that. 👍🏼
