### ISSUE TITLE
Do not use Google Fonts

### ISSUE THREAD

**Issue by DanielRuf** [matsuyoshi30/harbor#12]
https://github.com/matsuyoshi30/harbor/blob/dd7598175fde2eb3418c0b2e9eddaa28e631fe94/layouts/partials/head.html#L14

These files should be selfhosted using https://google-webfonts-helper.herokuapp.com/

**Comment by matsuyoshi30** [comment]
I didn't know about https://google-webfonts-helper.herokuapp.com/
Thanks for letting me know!

**Comment by DanielRuf** [comment]
You can optimize it further =)

Remove all except woff2 and woff and load woff2 first. Smaller font files (better compression) and better features.

**Comment by matsuyoshi30** [comment]
📝 https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization#webfont_formats

**Comment by matsuyoshi30** [comment]
Thanks again! I've done :)
