### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Briy09** [matsuyoshi30/harbor#19]
1.Found  [instant.page](https://instant.page/), it can speed up the web pages.
`<script src="https://cdn.jsdelivr.net/npm/instant.page@3.0.0/instantpage.min.js" type="module" defer></script>`

2.about the comments, here are some references.
https://talk.hyvor.com/
https://github.com/zzossig/hugo-theme-zzo/tree/master/layouts/partials/comments

Stay home,wash hands,wear mask.Hope everyone is healthy.

**Comment by matsuyoshi30** [comment]
> Stay home,wash hands,wear mask.Hope everyone is healthy.

:+1:
