### ISSUE TITLE
Add archive page

### ISSUE THREAD

**Issue by matsuyoshi30** [matsuyoshi30/harbor#2]

**Comment by Briy09** [comment]
and Pagination too😄

**Comment by matsuyoshi30** [comment]
Hi @Briy09!

I implemented pagination like below. ([demo](https://themes.gohugo.io/theme/harbor/) page)
https://github.com/matsuyoshi30/harbor/blob/ed244575e9d72fa42fe7970a28777550a798bef4/layouts/_default/list.html#L14-L27

Are you saying something different?

**Comment by Briy09** [comment]
What I mean is the archive page ( https://themes.gohugo.io//theme/harbor/post/ ) should only include the date, title and pagination,not include summary and "Read More".
Just like https://blog.olowolo.com/example-site/post/

**Comment by matsuyoshi30** [comment]
@Briy09 Got it. I think so too!

**Comment by matsuyoshi30** [comment]
once, I implemented without pagination.
ref: https://parsiya.net/archive/
