### ISSUE TITLE
Dark Mode broken on Safari

### ISSUE THREAD

**Issue by nicolinuxfr** [matsuyoshi30/harbor#20]
On my iPhone and on my iPad, both on Safari using the latest iOS 13.4 version, dark mode is broken. By that, I mean I have white space on top of the page, and white background again from some point on the page. 

Pictures will tell more than words : 

![D8BE3A81-9FCC-4295-A3AF-522F00BC4481](https://user-images.githubusercontent.com/2078386/77859978-c0521400-720c-11ea-88b7-ab2cea4881ad.png)

![42A2355D-F8BB-4388-A934-35D2270AAB65](https://user-images.githubusercontent.com/2078386/77859980-c3e59b00-720c-11ea-8eda-b165ed363ad3.png)

I can check tomorrow if it’s the same on desktop browsers, but I suppose it is. 

I’m using the theme as a Hugo submodule, with the latest commit. Let me know if you need more information. 

And thanks for your work ! 👍

**Comment by matsuyoshi30** [comment]
Hi @nicolinuxfr!
Thank you for letting me know about that problem. This looks so bad... I'll fix that as soon as possible!

**Comment by nicolinuxfr** [comment]
Thanks ! :-)

In the meantime, I can confirm it's not only on iOS. The macOS version of Safari has the same behaviour.

Firefox and Chrome are fine, though.

**Comment by matsuyoshi30** [comment]
@nicolinuxfr 

I fixed this issue. If you still have problems, please let me know!

**Comment by nicolinuxfr** [comment]
As far as I can tell, it's perfect now. 

Thanks for your work ! 👍
