### ISSUE TITLE
Render Issues

### ISSUE THREAD

**Issue by thinhtranphuc** [matsuyoshi30/harbor#24]
Hi, I really like your theme but unfortunately it renders inappropriately recently. Please have a look on the attachment. It did work when I was using blowdown::server_site() but not with blogdown::hugo_build().  I hope it will be sorted out soon.
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/48721649/77935289-72581180-72db-11ea-85f9-099630be2a1a.png">

**Comment by matsuyoshi30** [comment]
Hi @thinhtranphuc!
Thank you for letting me know, but I couldn't reproduce it so I want to know more details.
Could you share your `config.toml` and blog repository?

**Comment by thinhtranphuc** [comment]
Hi @matsuyoshi30,  thank you for response. Here is my blog repository. https://github.com/thinhtranphuc/blogdown and my config.toml is as below. I am new to these things so I am sorry if I bother you because of my mistakes. 

theme = "harbor"
baseURL = "https://gohugo.io"
title = "Code Pad"
author = "Thinh"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[Author]
  name = "thinh"

[outputs]
    section = ["JSON", "HTML"]

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 3

[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "tags"
  weight = 3

[[params.nav]]
  identifier = "search"
  name = "Search"
  icon = "fas fa-search fa-lg"
  url = "search"
  weight = 3

[params]
  mainSections = ["post"]
  favicon = "favicon.ico"

  [params.logo]
    url = "icon.png"
    width = 50
    height = 50
    alt = "Logo"

**Comment by matsuyoshi30** [comment]
@thinhtranphuc 

Thank you for sharing the information!
I'm sorry, I don't figure out what happens yet. I knew about [blogdown](https://bookdown.org/yihui/blogdown/) for the first time, so it will take some time but I continue to investigate.

btw, I think you've not made this theme submodule for your blog, so please try the below steps!

```
$ cd [your blogdown repository]
$ git submodule deinit -f themes/harbor
$ git rm -rf themes/harbor
$ git submodule add https://github.com/matsuyoshi30/harbor.git themes/harbor
```

**Comment by thinhtranphuc** [comment]
Hi @matsuyoshi30, I will follow your instructions. Thank you very much
