### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Briy09** [matsuyoshi30/harbor#3]
Simple theme！Good！Hope add some feature.
1. categories page
2. [Table of Contents](https://gohugo.io/content-management/toc/)
3. back to top
4. search
https://koirand.github.io/blog/
https://koirand.github.io/blog/2018/pulp-search/

**Comment by matsuyoshi30** [comment]
Thank you for feature request!!! I will try to implement those features.

**Comment by matsuyoshi30** [comment]
@Briy09 Done. Thank you for your feature request 👍
