### ISSUE TITLE
Feature Request: Add Matomo Analytic option

### ISSUE THREAD

**Issue by cb3inco** [matsuyoshi30/harbor#34]
Would love to see Matomo analytic option as well. Thanks.

**Comment by advaithm** [comment]
I'd like to take a shot doesn't seem to hard to do

**Comment by lomion0815** [comment]
I prepared a commit for this: [https://github.com/lomion0815/harbor/tree/matomo](lomion0815/harbor) (Branch Matomo) but I don't have any means to test it. You just need to create a file (static/matomo.js) with the Matomo JavaScript tag.
Please provide feedback.
If needed I can provide a PR for it.

**Comment by matsuyoshi30** [comment]
Closed by #102
