### ISSUE TITLE
Search button is broken in demo

### ISSUE THREAD

**Issue by IronicBadger** [matsuyoshi30/harbor#35]
As per title.

**Comment by matsuyoshi30** [comment]
@IronicBadger Thank you for reporting issue! I fixed and am waiting update https://github.com/gohugoio/hugoThemes/commits/master ...

**Comment by matsuyoshi30** [comment]
I misunderstood this issue. I need to request for adding my theme to whitelist in [the public repository](https://github.com/gohugoio/hugoThemes).
I've done [that](https://github.com/gohugoio/hugoThemes/issues/892). Waiting to accept it!
