### ISSUE TITLE
Running with Hugo throws warnings for Page.URL's future deprecation

### ISSUE THREAD

**Issue by loganrios** [matsuyoshi30/harbor#41]
Exact warning (personal/timing details emitted):
```
$ hugo server -D
Building sites … WARN YYYY/MM/DD HH:MM:SS Page.URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url
```

Not sure what's causing this--I've messed around with removing `url` from `[[params.*]]` in the `config.toml` file, but the error still gets thrown. 

In looking through the source code my (uneducated) guess is that it could be `layouts/partials/nav.html`'s use of `{{ .url | relLangURL }}`, but I haven't figured out how to rebuild with those parts changed.

**Comment by matsuyoshi30** [comment]
@loganrios Thank you for letting me know this problem. That is caused by `layouts/_defaults/rss.xml`.
