### ISSUE TITLE
Disable disqus on some pages

### ISSUE THREAD

**Issue by advaithm** [matsuyoshi30/harbor#45]
I added this to single.html which disabled disqus on some pages. if  `disable_comments: true ` is in the params
```
 {{ if  (not (isset .Params "disable_comments")) }}
    {{ partial "disqus.html" . }}
  {{ end }}
```
It would be nice if this was part of the theme. If you feel this is not required i understand and you can close this issue

**Comment by matsuyoshi30** [comment]
Looks good to me. Thank you for adding a new feature!

**Comment by advaithm** [comment]
No problem
