### ISSUE TITLE
Search on Demo site not working

### ISSUE THREAD

**Issue by damien1** [matsuyoshi30/harbor#47]
Hi

love the theme - but wondering if you can make search work on the demo?

I tried typing in tags like CSS or Emoji and pressing enter - but nothing happens

**Comment by matsuyoshi30** [comment]
@damien1 Hi.
I think the URL should have a trailing slash (https://themes.gohugo.io/theme/harbor/search/) to the search work correctly.
I'm trying to fix it. Thanks for letting me know about this problem.

**Comment by matsuyoshi30** [comment]
Done!
