### ISSUE TITLE
Pages loading slow.

### ISSUE THREAD

**Issue by Lunarequest** [matsuyoshi30/harbor#50]
I use your theme in my blog. Recently I moved to self hosting my blog. One thing a lot of people were saying is that the page was loading very slowly. After doing some research its because data is read in from json on the client side. Is there a simple way to fix this like using  a program to assemble the page client side or do changes need to be made to the theme? currently I am sending all  the files via nginx. 

if you want to see what I mean go to <https://nullrequest.com> it takes 5~6 seconds to load.

**Comment by matsuyoshi30** [comment]
@advaithm 
Thank you for letting me know about this issue.
I'm trying to improve page loading but I fixed the font loading.

**Comment by advaithm** [comment]
@matsuyoshi30 one thing that is really slowing down the loading is that rendering of the page is done client said with data being written in from the JSON. This greatly increase the loading time. optimizing the rendering client side or having the html be made on the server will definitely increase the loading speed.

**Comment by advaithm** [comment]
@matsuyoshi30 I managed to increase the speed of the page loading by using gzip compression in my nginx config. It loads pretty fast on a desktop platform but on mobile devices its still very slow. as shown [here](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fnullrequest.com&tab=mobile) the main issue appears to be js and css that are not used on mobile devices. maybe it could be possible if 2 pages are generated one for mobile users and one for regular users?

**Comment by advaithm** [comment]
@matsuyoshi30 would if be possible to preload fonts instead of loading them in css. [this](https://web.dev/codelab-preload-web-fonts/) shows what I mean in practice

**Comment by advaithm** [comment]
Desktop performance is pretty good but on mobile for some reason this theme just can't do well

**Comment by Lunarequest** [comment]
This can be closed now, the latest version has the same performance on mobile and desktop, which is routinely above 90 on page insights
