### ISSUE TITLE
override CSS in harbor theme

### ISSUE THREAD

**Issue by rericsson** [matsuyoshi30/harbor#55]
I like the harbor theme and am using it on my blog (https://l10systems.com). Thanks for the nice work.

A question: some themes have a parameter that allow you to override css. It's typically something like `css = ["css/custom.css"]` and you then add that file to the static/css directory with your overrides. 

I don't see this feature in harbor. How can I override css? In my case, I just want to change some font colors? I can probably hack it in but wanted to check if I was missing something.

**Comment by matsuyoshi30** [comment]
Hi @rericsson 
Thanks for adding this issue. The feature that the users can override CSS in this theme has not implemented yet but sounds great to me. I'll add this feature this weekend.

**Comment by rericsson** [comment]
Thanks! It works great.
