### ISSUE TITLE
render problem

### ISSUE THREAD

**Issue by zwtmyeot** [matsuyoshi30/harbor#6]
I follow the [quick start](https://gohugo.io/getting-started/quick-start/) which tell me use the command to create my post: 

```sh
hugo new posts/my-post.md
```

but I found that the rendering of the page is not correct. After few hours searching, I found I should use:

```sh
hugo new post/my-post.md
```

to get the correct rendering.

I think maybe someone will encounter this problem too, so I hope you can point out this in the guide.

By the way, I love this concise theme, thank you for your work!

**Comment by matsuyoshi30** [comment]
@zwtmyeot  Thank you for letting me know about that problem!
I fixed `README.md`. If you think it does not enough, please PR!!!
