### ISSUE TITLE
use instantpage.min.js over instantpage.js

### ISSUE THREAD

**Issue by advaithm** [matsuyoshi30/harbor#63]
instantpage.js has a minified version which will offer lower bandwidth usage if used [this repo](https://github.com/instantpage/instant.page) has a method on how to minify instsantpage.js maybe this could be added to npm build prod?

**Comment by matsuyoshi30** [comment]
@advaithm I think it is enough to generate instantpage.min.js and put it into `static/js` dir instead  of instantpage.js. I'll try this.

**Comment by advaithm** [comment]
That should be enough.
