### ISSUE TITLE
Theme randomly switches

### ISSUE THREAD

**Issue by advaithm** [matsuyoshi30/harbor#64]
There is a strange bug where the theme will switch from dark to light when the webpage loads with out the user changing the theme.

**Comment by matsuyoshi30** [comment]
Hmm, that is very strange... I'll try to make `static/src/theme.js` better.

**Comment by lomion0815** [comment]
@advaithm you mean with "switch" the loading of each page in darkmode and then changing to light once the page has completely loaded? I fixed that behaviour with #72

**Comment by advaithm** [comment]
Yup that's what I mean

**Comment by lomion0815** [comment]
Then check out PR #72

**Comment by matsuyoshi30** [comment]
@lomion0815 Thanks for solving this issue. I think I should make `static/src/theme.js` better too. I'll fix it another PR.
