### ISSUE TITLE
How does bundle.js gets generated?

### ISSUE THREAD

**Issue by hasan-hasanov** [matsuyoshi30/harbor#79]
Hi,

Thanks for the great theme. I want to change some things but it seems to always end up in bundle.js javascript file.
How does this file gets generated?
How can I edit it in human readable language and regenerate it?

The thing I want to do is to remove Roboto font and replace it with Helvetica for example.

Best Regards

**Comment by matsuyoshi30** [comment]
@hasan-hasanov Hi! Thanks for your comment.

JavaScript source file is in `static/src` directory. And if you want to change fonts, please check CSS file which is in `static/css`.

What I said is [README](https://github.com/matsuyoshi30/harbor#development), so you could find this helpful!

**Comment by hasan-hasanov** [comment]
Thank you for answering.

I will close the issue. 

Have a nice day! :)
