### ISSUE TITLE
Disable comments in front matter doesn't work for specific pages.

### ISSUE THREAD

**Issue by bershatsky** [matsuyoshi30/harbor#87]
I'm following the instructions and inserting this code on the frontmatter of a given post:

disable_comment = true 

That causes Hugo to crash.

Please help.

**Comment by matsuyoshi30** [comment]
@bershatsky Thanks for reporting. The example in the README has typo. The correct example is `disable_comments`.

I'll fix README later.

**Comment by bershatsky** [comment]
thanks!
