### ISSUE TITLE
index.json Not found

### ISSUE THREAD

**Issue by h2kyaw** [matsuyoshi30/harbor#92]
I got Error "Failed to load resource: the server responded with a status of 404 (Not Found) :1313/2021/post/index.json:1" at Inspect Window.

My Config.toml

[permalinks]
	post = "/:year/:filename/"
	page = "/:filename/"

[outputs]
    section = ["JSON", "HTML", "RSS"]

**Comment by matsuyoshi30** [comment]
Hi @h2kyaw, sorry for the delay.

Could you tell me the details like `config.toml` contents and the project's repository?
